// =============================================================================
// DEPARTAMENTOS Y MUNICIPIOS DE COLOMBIA
// Fuente: DANE - Division Politico Administrativa (DIVIPOLA)
// Solo municipios con vocacion agricola principal incluidos en seed base
// =============================================================================

export const departamentos = [
  { codigo: "05", nombre: "Antioquia" },
  { codigo: "08", nombre: "Atlantico" },
  { codigo: "11", nombre: "Bogota D.C." },
  { codigo: "13", nombre: "Bolivar" },
  { codigo: "15", nombre: "Boyaca" },
  { codigo: "17", nombre: "Caldas" },
  { codigo: "18", nombre: "Caqueta" },
  { codigo: "19", nombre: "Cauca" },
  { codigo: "20", nombre: "Cesar" },
  { codigo: "23", nombre: "Cordoba" },
  { codigo: "25", nombre: "Cundinamarca" },
  { codigo: "27", nombre: "Choco" },
  { codigo: "41", nombre: "Huila" },
  { codigo: "44", nombre: "La Guajira" },
  { codigo: "47", nombre: "Magdalena" },
  { codigo: "50", nombre: "Meta" },
  { codigo: "52", nombre: "Narino" },
  { codigo: "54", nombre: "Norte de Santander" },
  { codigo: "63", nombre: "Quindio" },
  { codigo: "66", nombre: "Risaralda" },
  { codigo: "68", nombre: "Santander" },
  { codigo: "70", nombre: "Sucre" },
  { codigo: "73", nombre: "Tolima" },
  { codigo: "76", nombre: "Valle del Cauca" },
] as const;

// Municipios principales por departamento (seed inicial)
// Se puede ampliar con el DIVIPOLA completo (1122 municipios)
export const municipios = [
  // Antioquia - 05
  { codigo: "05001", nombre: "Medellin", departamentoCod: "05" },
  { codigo: "05088", nombre: "Bello", departamentoCod: "05" },
  { codigo: "05318", nombre: "Guarne", departamentoCod: "05" },
  { codigo: "05360", nombre: "Jardin", departamentoCod: "05" },
  { codigo: "05400", nombre: "La Ceja", departamentoCod: "05" },
  { codigo: "05411", nombre: "La Union", departamentoCod: "05" },
  { codigo: "05607", nombre: "Retiro", departamentoCod: "05" },
  { codigo: "05615", nombre: "Rionegro", departamentoCod: "05" },
  { codigo: "05790", nombre: "Santa Barbara", departamentoCod: "05" },
  { codigo: "05885", nombre: "Urrao", departamentoCod: "05" },

  // Boyaca - 15
  { codigo: "15001", nombre: "Tunja", departamentoCod: "15" },
  { codigo: "15022", nombre: "Aquitania", departamentoCod: "15" },
  { codigo: "15090", nombre: "Berbeo", departamentoCod: "15" },
  { codigo: "15187", nombre: "Chiquinquira", departamentoCod: "15" },
  { codigo: "15476", nombre: "Moniquira", departamentoCod: "15" },
  { codigo: "15572", nombre: "Raquira", departamentoCod: "15" },
  { codigo: "15667", nombre: "Samaca", departamentoCod: "15" },
  { codigo: "15720", nombre: "Sogamoso", departamentoCod: "15" },
  { codigo: "15740", nombre: "Soracá", departamentoCod: "15" },
  { codigo: "15763", nombre: "Tibasosa", departamentoCod: "15" },
  { codigo: "15810", nombre: "Tuta", departamentoCod: "15" },
  { codigo: "15832", nombre: "Ventaquemada", departamentoCod: "15" },

  // Caldas - 17
  { codigo: "17001", nombre: "Manizales", departamentoCod: "17" },
  { codigo: "17174", nombre: "Chinchina", departamentoCod: "17" },
  { codigo: "17380", nombre: "La Dorada", departamentoCod: "17" },
  { codigo: "17433", nombre: "Manzanares", departamentoCod: "17" },
  { codigo: "17524", nombre: "Pacora", departamentoCod: "17" },
  { codigo: "17541", nombre: "Palestina", departamentoCod: "17" },
  { codigo: "17616", nombre: "Riosucio", departamentoCod: "17" },
  { codigo: "17777", nombre: "Supia", departamentoCod: "17" },
  { codigo: "17867", nombre: "Villamaria", departamentoCod: "17" },

  // Cauca - 19
  { codigo: "19001", nombre: "Popayan", departamentoCod: "19" },
  { codigo: "19022", nombre: "Almaguer", departamentoCod: "19" },
  { codigo: "19050", nombre: "Argelia", departamentoCod: "19" },
  { codigo: "19300", nombre: "Florencia", departamentoCod: "19" },
  { codigo: "19318", nombre: "Guachene", departamentoCod: "19" },
  { codigo: "19573", nombre: "Puerto Tejada", departamentoCod: "19" },

  // Cundinamarca - 25
  { codigo: "25001", nombre: "Agua de Dios", departamentoCod: "25" },
  { codigo: "25175", nombre: "Choachi", departamentoCod: "25" },
  { codigo: "25200", nombre: "Cota", departamentoCod: "25" },
  { codigo: "25214", nombre: "Cucunuba", departamentoCod: "25" },
  { codigo: "25269", nombre: "Facatativa", departamentoCod: "25" },
  { codigo: "25290", nombre: "Funza", departamentoCod: "25" },
  { codigo: "25307", nombre: "Fusagasuga", departamentoCod: "25" },
  { codigo: "25386", nombre: "La Mesa", departamentoCod: "25" },
  { codigo: "25430", nombre: "Macheta", departamentoCod: "25" },
  { codigo: "25473", nombre: "Mosquera", departamentoCod: "25" },
  { codigo: "25483", nombre: "Nemocon", departamentoCod: "25" },
  { codigo: "25658", nombre: "Sibate", departamentoCod: "25" },
  { codigo: "25754", nombre: "Soacha", departamentoCod: "25" },
  { codigo: "25785", nombre: "Subachoque", departamentoCod: "25" },
  { codigo: "25843", nombre: "Tocaima", departamentoCod: "25" },
  { codigo: "25899", nombre: "Zipaquira", departamentoCod: "25" },

  // Huila - 41
  { codigo: "41001", nombre: "Neiva", departamentoCod: "41" },
  { codigo: "41006", nombre: "Acevedo", departamentoCod: "41" },
  { codigo: "41013", nombre: "Agrado", departamentoCod: "41" },
  { codigo: "41016", nombre: "Aipe", departamentoCod: "41" },
  { codigo: "41132", nombre: "Campo Alegre", departamentoCod: "41" },
  { codigo: "41206", nombre: "El Agrado", departamentoCod: "41" },
  { codigo: "41298", nombre: "Garzon", departamentoCod: "41" },
  { codigo: "41306", nombre: "Gigante", departamentoCod: "41" },
  { codigo: "41503", nombre: "Palermo", departamentoCod: "41" },
  { codigo: "41548", nombre: "Pitalito", departamentoCod: "41" },
  { codigo: "41770", nombre: "San Agustin", departamentoCod: "41" },
  { codigo: "41791", nombre: "Santa Maria", departamentoCod: "41" },
  { codigo: "41872", nombre: "Timana", departamentoCod: "41" },

  // Nariño - 52
  { codigo: "52001", nombre: "Pasto", departamentoCod: "52" },
  { codigo: "52019", nombre: "Alban", departamentoCod: "52" },
  { codigo: "52240", nombre: "El Tambo", departamentoCod: "52" },
  { codigo: "52256", nombre: "Funes", departamentoCod: "52" },
  { codigo: "52418", nombre: "La Florida", departamentoCod: "52" },
  { codigo: "52490", nombre: "Montalvo", departamentoCod: "52" },
  { codigo: "52506", nombre: "Olaya Herrera", departamentoCod: "52" },
  { codigo: "52694", nombre: "Samaniego", departamentoCod: "52" },
  { codigo: "52720", nombre: "Sandona", departamentoCod: "52" },
  { codigo: "52835", nombre: "Tumaco", departamentoCod: "52" },

  // Quindio - 63
  { codigo: "63001", nombre: "Armenia", departamentoCod: "63" },
  { codigo: "63111", nombre: "Buenavista", departamentoCod: "63" },
  { codigo: "63130", nombre: "Calarca", departamentoCod: "63" },
  { codigo: "63190", nombre: "Circasia", departamentoCod: "63" },
  { codigo: "63212", nombre: "Cordoba", departamentoCod: "63" },
  { codigo: "63272", nombre: "Filandia", departamentoCod: "63" },
  { codigo: "63302", nombre: "Genova", departamentoCod: "63" },
  { codigo: "63401", nombre: "La Tebaida", departamentoCod: "63" },
  { codigo: "63470", nombre: "Montenegro", departamentoCod: "63" },
  { codigo: "63548", nombre: "Pijao", departamentoCod: "63" },
  { codigo: "63594", nombre: "Quimbaya", departamentoCod: "63" },
  { codigo: "63690", nombre: "Salento", departamentoCod: "63" },

  // Risaralda - 66
  { codigo: "66001", nombre: "Pereira", departamentoCod: "66" },
  { codigo: "66045", nombre: "Apia", departamentoCod: "66" },
  { codigo: "66075", nombre: "Balboa", departamentoCod: "66" },
  { codigo: "66170", nombre: "Dosquebradas", departamentoCod: "66" },
  { codigo: "66318", nombre: "Guatica", departamentoCod: "66" },
  { codigo: "66383", nombre: "La Celia", departamentoCod: "66" },
  { codigo: "66400", nombre: "La Virginia", departamentoCod: "66" },
  { codigo: "66440", nombre: "Marsella", departamentoCod: "66" },
  { codigo: "66456", nombre: "Mistrato", departamentoCod: "66" },
  { codigo: "66572", nombre: "Pueblo Rico", departamentoCod: "66" },
  { codigo: "66594", nombre: "Quinchia", departamentoCod: "66" },
  { codigo: "66682", nombre: "Santa Rosa de Cabal", departamentoCod: "66" },
  { codigo: "66687", nombre: "Santuario", departamentoCod: "66" },

  // Santander - 68
  { codigo: "68001", nombre: "Bucaramanga", departamentoCod: "68" },
  { codigo: "68013", nombre: "Aguada", departamentoCod: "68" },
  { codigo: "68020", nombre: "Albania", departamentoCod: "68" },
  { codigo: "68077", nombre: "Barbosa", departamentoCod: "68" },
  { codigo: "68132", nombre: "Capitanejo", departamentoCod: "68" },
  { codigo: "68179", nombre: "Charta", departamentoCod: "68" },
  { codigo: "68209", nombre: "Curiti", departamentoCod: "68" },
  { codigo: "68245", nombre: "El Carmen de Chucuri", departamentoCod: "68" },
  { codigo: "68307", nombre: "Giron", departamentoCod: "68" },
  { codigo: "68432", nombre: "Macaravita", departamentoCod: "68" },
  { codigo: "68444", nombre: "Matanza", departamentoCod: "68" },
  { codigo: "68464", nombre: "Mogotes", departamentoCod: "68" },
  { codigo: "68547", nombre: "Pie de Cuesta", departamentoCod: "68" },
  { codigo: "68575", nombre: "Puente Nacional", departamentoCod: "68" },
  { codigo: "68679", nombre: "San Vicente de Chucuri", departamentoCod: "68" },
  { codigo: "68754", nombre: "Socorro", departamentoCod: "68" },
  { codigo: "68780", nombre: "Suaita", departamentoCod: "68" },
  { codigo: "68855", nombre: "Velez", departamentoCod: "68" },

  // Tolima - 73
  { codigo: "73001", nombre: "Ibague", departamentoCod: "73" },
  { codigo: "73024", nombre: "Alpujarra", departamentoCod: "73" },
  { codigo: "73043", nombre: "Anzoategui", departamentoCod: "73" },
  { codigo: "73055", nombre: "Armero", departamentoCod: "73" },
  { codigo: "73124", nombre: "Cajamarca", departamentoCod: "73" },
  { codigo: "73168", nombre: "Chaparral", departamentoCod: "73" },
  { codigo: "73200", nombre: "Coello", departamentoCod: "73" },
  { codigo: "73275", nombre: "Flandes", departamentoCod: "73" },
  { codigo: "73283", nombre: "Fresno", departamentoCod: "73" },
  { codigo: "73349", nombre: "Honda", departamentoCod: "73" },
  { codigo: "73411", nombre: "Lerida", departamentoCod: "73" },
  { codigo: "73443", nombre: "Mariquita", departamentoCod: "73" },
  { codigo: "73449", nombre: "Melgar", departamentoCod: "73" },
  { codigo: "73520", nombre: "Ortega", departamentoCod: "73" },
  { codigo: "73563", nombre: "Planadas", departamentoCod: "73" },
  { codigo: "73616", nombre: "Rioblanco", departamentoCod: "73" },
  { codigo: "73678", nombre: "San Luis", departamentoCod: "73" },
  { codigo: "73861", nombre: "Villahermosa", departamentoCod: "73" },

  // Valle del Cauca - 76
  { codigo: "76001", nombre: "Cali", departamentoCod: "76" },
  { codigo: "76036", nombre: "Andalucia", departamentoCod: "76" },
  { codigo: "76041", nombre: "Ansermanuevo", departamentoCod: "76" },
  { codigo: "76113", nombre: "Buga", departamentoCod: "76" },
  { codigo: "76122", nombre: "Bugalagrande", departamentoCod: "76" },
  { codigo: "76130", nombre: "Caicedonia", departamentoCod: "76" },
  { codigo: "76147", nombre: "Cartago", departamentoCod: "76" },
  { codigo: "76246", nombre: "El Cairo", departamentoCod: "76" },
  { codigo: "76248", nombre: "El Cerrito", departamentoCod: "76" },
  { codigo: "76306", nombre: "Ginebra", departamentoCod: "76" },
  { codigo: "76318", nombre: "Guacari", departamentoCod: "76" },
  { codigo: "76364", nombre: "La Union", departamentoCod: "76" },
  { codigo: "76377", nombre: "La Victoria", departamentoCod: "76" },
  { codigo: "76400", nombre: "Obando", departamentoCod: "76" },
  { codigo: "76497", nombre: "Palmira", departamentoCod: "76" },
  { codigo: "76520", nombre: "Pradera", departamentoCod: "76" },
  { codigo: "76606", nombre: "Restrepo", departamentoCod: "76" },
  { codigo: "76616", nombre: "Riofrio", departamentoCod: "76" },
  { codigo: "76622", nombre: "Roldanillo", departamentoCod: "76" },
  { codigo: "76670", nombre: "San Pedro", departamentoCod: "76" },
  { codigo: "76736", nombre: "Sevilla", departamentoCod: "76" },
  { codigo: "76823", nombre: "Toro", departamentoCod: "76" },
  { codigo: "76828", nombre: "Trujillo", departamentoCod: "76" },
  { codigo: "76845", nombre: "Tulua", departamentoCod: "76" },
  { codigo: "76863", nombre: "Ulloa", departamentoCod: "76" },
  { codigo: "76869", nombre: "Versalles", departamentoCod: "76" },
  { codigo: "76890", nombre: "Vijes", departamentoCod: "76" },
  { codigo: "76892", nombre: "Yotoco", departamentoCod: "76" },
  { codigo: "76895", nombre: "Yumbo", departamentoCod: "76" },
  { codigo: "76897", nombre: "Zarzal", departamentoCod: "76" },
] as const;
