// =============================================================================
// PAISES DEL MUNDO
// Fuente: ISO 3166-1 alpha-3, nombres en español
// =============================================================================

export const paises = [
  { codigo: "AFG", nombre: "Afganistan" },
  { codigo: "ALB", nombre: "Albania" },
  { codigo: "DEU", nombre: "Alemania" },
  { codigo: "AND", nombre: "Andorra" },
  { codigo: "AGO", nombre: "Angola" },
  { codigo: "ATG", nombre: "Antigua y Barbuda" },
  { codigo: "SAU", nombre: "Arabia Saudita" },
  { codigo: "DZA", nombre: "Argelia" },
  { codigo: "ARG", nombre: "Argentina" },
  { codigo: "ARM", nombre: "Armenia" },
  { codigo: "AUS", nombre: "Australia" },
  { codigo: "AUT", nombre: "Austria" },
  { codigo: "AZE", nombre: "Azerbaiyan" },
  { codigo: "BHS", nombre: "Bahamas" },
  { codigo: "BHR", nombre: "Bahrein" },
  { codigo: "BGD", nombre: "Bangladesh" },
  { codigo: "BRB", nombre: "Barbados" },
  { codigo: "BEL", nombre: "Belgica" },
  { codigo: "BLZ", nombre: "Belice" },
  { codigo: "BEN", nombre: "Benin" },
  { codigo: "BTN", nombre: "Bhutan" },
  { codigo: "BLR", nombre: "Bielorrusia" },
  { codigo: "MMR", nombre: "Birmania (Myanmar)" },
  { codigo: "BOL", nombre: "Bolivia" },
  { codigo: "BIH", nombre: "Bosnia y Herzegovina" },
  { codigo: "BWA", nombre: "Botsuana" },
  { codigo: "BRA", nombre: "Brasil" },
  { codigo: "BRN", nombre: "Brunei" },
  { codigo: "BGR", nombre: "Bulgaria" },
  { codigo: "BFA", nombre: "Burkina Faso" },
  { codigo: "BDI", nombre: "Burundi" },
  { codigo: "CPV", nombre: "Cabo Verde" },
  { codigo: "KHM", nombre: "Camboya" },
  { codigo: "CMR", nombre: "Camerun" },
  { codigo: "CAN", nombre: "Canada" },
  { codigo: "QAT", nombre: "Catar" },
  { codigo: "TCD", nombre: "Chad" },
  { codigo: "CHL", nombre: "Chile" },
  { codigo: "CHN", nombre: "China" },
  { codigo: "CYP", nombre: "Chipre" },
  { codigo: "VAT", nombre: "Ciudad del Vaticano" },
  { codigo: "COL", nombre: "Colombia" },
  { codigo: "COM", nombre: "Comoras" },
  { codigo: "PRK", nombre: "Corea del Norte" },
  { codigo: "KOR", nombre: "Corea del Sur" },
  { codigo: "CIV", nombre: "Costa de Marfil" },
  { codigo: "CRI", nombre: "Costa Rica" },
  { codigo: "HRV", nombre: "Croacia" },
  { codigo: "CUB", nombre: "Cuba" },
  { codigo: "DNK", nombre: "Dinamarca" },
  { codigo: "DMA", nombre: "Dominica" },
  { codigo: "ECU", nombre: "Ecuador" },
  { codigo: "EGY", nombre: "Egipto" },
  { codigo: "SLV", nombre: "El Salvador" },
  { codigo: "ARE", nombre: "Emiratos Arabes Unidos" },
  { codigo: "ERI", nombre: "Eritrea" },
  { codigo: "SVK", nombre: "Eslovaquia" },
  { codigo: "SVN", nombre: "Eslovenia" },
  { codigo: "ESP", nombre: "España" },
  { codigo: "USA", nombre: "Estados Unidos" },
  { codigo: "EST", nombre: "Estonia" },
  { codigo: "ETH", nombre: "Etiopia" },
  { codigo: "PHL", nombre: "Filipinas" },
  { codigo: "FIN", nombre: "Finlandia" },
  { codigo: "FJI", nombre: "Fiyi" },
  { codigo: "FRA", nombre: "Francia" },
  { codigo: "GAB", nombre: "Gabon" },
  { codigo: "GMB", nombre: "Gambia" },
  { codigo: "GEO", nombre: "Georgia" },
  { codigo: "GHA", nombre: "Ghana" },
  { codigo: "GRD", nombre: "Granada" },
  { codigo: "GRC", nombre: "Grecia" },
  { codigo: "GTM", nombre: "Guatemala" },
  { codigo: "GUY", nombre: "Guyana" },
  { codigo: "GNQ", nombre: "Guinea Ecuatorial" },
  { codigo: "GIN", nombre: "Guinea" },
  { codigo: "GNB", nombre: "Guinea-Bisau" },
  { codigo: "HTI", nombre: "Haiti" },
  { codigo: "HND", nombre: "Honduras" },
  { codigo: "HUN", nombre: "Hungria" },
  { codigo: "IND", nombre: "India" },
  { codigo: "IDN", nombre: "Indonesia" },
  { codigo: "IRQ", nombre: "Irak" },
  { codigo: "IRN", nombre: "Iran" },
  { codigo: "IRL", nombre: "Irlanda" },
  { codigo: "ISL", nombre: "Islandia" },
  { codigo: "MHL", nombre: "Islas Marshall" },
  { codigo: "SLB", nombre: "Islas Salomon" },
  { codigo: "ISR", nombre: "Israel" },
  { codigo: "ITA", nombre: "Italia" },
  { codigo: "JAM", nombre: "Jamaica" },
  { codigo: "JPN", nombre: "Japon" },
  { codigo: "JOR", nombre: "Jordania" },
  { codigo: "KAZ", nombre: "Kazajistan" },
  { codigo: "KEN", nombre: "Kenia" },
  { codigo: "KGZ", nombre: "Kirguistan" },
  { codigo: "KIR", nombre: "Kiribati" },
  { codigo: "KWT", nombre: "Kuwait" },
  { codigo: "LAO", nombre: "Laos" },
  { codigo: "LSO", nombre: "Lesoto" },
  { codigo: "LVA", nombre: "Letonia" },
  { codigo: "LBN", nombre: "Libano" },
  { codigo: "LBR", nombre: "Liberia" },
  { codigo: "LBY", nombre: "Libia" },
  { codigo: "LIE", nombre: "Liechtenstein" },
  { codigo: "LTU", nombre: "Lituania" },
  { codigo: "LUX", nombre: "Luxemburgo" },
  { codigo: "MKD", nombre: "Macedonia del Norte" },
  { codigo: "MDG", nombre: "Madagascar" },
  { codigo: "MYS", nombre: "Malasia" },
  { codigo: "MWI", nombre: "Malaui" },
  { codigo: "MDV", nombre: "Maldivas" },
  { codigo: "MLI", nombre: "Mali" },
  { codigo: "MLT", nombre: "Malta" },
  { codigo: "MAR", nombre: "Marruecos" },
  { codigo: "MUS", nombre: "Mauricio" },
  { codigo: "MRT", nombre: "Mauritania" },
  { codigo: "MEX", nombre: "Mexico" },
  { codigo: "FSM", nombre: "Micronesia" },
  { codigo: "MDA", nombre: "Moldavia" },
  { codigo: "MCO", nombre: "Monaco" },
  { codigo: "MNG", nombre: "Mongolia" },
  { codigo: "MNE", nombre: "Montenegro" },
  { codigo: "MOZ", nombre: "Mozambique" },
  { codigo: "NAM", nombre: "Namibia" },
  { codigo: "NRU", nombre: "Nauru" },
  { codigo: "NPL", nombre: "Nepal" },
  { codigo: "NIC", nombre: "Nicaragua" },
  { codigo: "NER", nombre: "Niger" },
  { codigo: "NGA", nombre: "Nigeria" },
  { codigo: "NOR", nombre: "Noruega" },
  { codigo: "NZL", nombre: "Nueva Zelanda" },
  { codigo: "OMN", nombre: "Oman" },
  { codigo: "NLD", nombre: "Paises Bajos" },
  { codigo: "PAK", nombre: "Pakistan" },
  { codigo: "PLW", nombre: "Palaos" },
  { codigo: "PAN", nombre: "Panama" },
  { codigo: "PNG", nombre: "Papua Nueva Guinea" },
  { codigo: "PRY", nombre: "Paraguay" },
  { codigo: "PER", nombre: "Peru" },
  { codigo: "POL", nombre: "Polonia" },
  { codigo: "PRT", nombre: "Portugal" },
  { codigo: "GBR", nombre: "Reino Unido" },
  { codigo: "CAF", nombre: "Republica Centroafricana" },
  { codigo: "CZE", nombre: "Republica Checa" },
  { codigo: "COD", nombre: "Republica Democratica del Congo" },
  { codigo: "COG", nombre: "Republica del Congo" },
  { codigo: "DOM", nombre: "Republica Dominicana" },
  { codigo: "RWA", nombre: "Ruanda" },
  { codigo: "ROU", nombre: "Rumania" },
  { codigo: "RUS", nombre: "Rusia" },
  { codigo: "WSM", nombre: "Samoa" },
  { codigo: "KNA", nombre: "San Cristobal y Nieves" },
  { codigo: "SMR", nombre: "San Marino" },
  { codigo: "VCT", nombre: "San Vicente y las Granadinas" },
  { codigo: "LCA", nombre: "Santa Lucia" },
  { codigo: "STP", nombre: "Santo Tome y Principe" },
  { codigo: "SEN", nombre: "Senegal" },
  { codigo: "SRB", nombre: "Serbia" },
  { codigo: "SYC", nombre: "Seychelles" },
  { codigo: "SLE", nombre: "Sierra Leona" },
  { codigo: "SGP", nombre: "Singapur" },
  { codigo: "SYR", nombre: "Siria" },
  { codigo: "SOM", nombre: "Somalia" },
  { codigo: "LKA", nombre: "Sri Lanka" },
  { codigo: "SWZ", nombre: "Suazilandia" },
  { codigo: "ZAF", nombre: "Sudafrica" },
  { codigo: "SDN", nombre: "Sudan" },
  { codigo: "SSD", nombre: "Sudan del Sur" },
  { codigo: "SWE", nombre: "Suecia" },
  { codigo: "CHE", nombre: "Suiza" },
  { codigo: "SUR", nombre: "Surinam" },
  { codigo: "THA", nombre: "Tailandia" },
  { codigo: "TZA", nombre: "Tanzania" },
  { codigo: "TJK", nombre: "Tayikistan" },
  { codigo: "TLS", nombre: "Timor Oriental" },
  { codigo: "TGO", nombre: "Togo" },
  { codigo: "TON", nombre: "Tonga" },
  { codigo: "TTO", nombre: "Trinidad y Tobago" },
  { codigo: "TUN", nombre: "Tunez" },
  { codigo: "TKM", nombre: "Turkmenistan" },
  { codigo: "TUR", nombre: "Turquia" },
  { codigo: "TUV", nombre: "Tuvalu" },
  { codigo: "UKR", nombre: "Ucrania" },
  { codigo: "UGA", nombre: "Uganda" },
  { codigo: "URY", nombre: "Uruguay" },
  { codigo: "UZB", nombre: "Uzbekistan" },
  { codigo: "VUT", nombre: "Vanuatu" },
  { codigo: "VEN", nombre: "Venezuela" },
  { codigo: "VNM", nombre: "Vietnam" },
  { codigo: "YEM", nombre: "Yemen" },
  { codigo: "DJI", nombre: "Yibuti" },
  { codigo: "ZMB", nombre: "Zambia" },
  { codigo: "ZWE", nombre: "Zimbabue" },
] as const;
