-- =============================================================================
-- AGROCHAIN - Catalogo completo de paises (ISO 3166-1 alpha-3, nombres en español)
-- Reemplaza el catalogo minimo (solo Colombia) de 08_parcelas_ubicacion.sql con
-- la lista completa de paises del mundo, para que el select de pais en el
-- formulario de predio sea un catalogo real seleccionable, no un valor fijo.
-- Fuente: packages/database/src/seed/paises.ts
-- =============================================================================

INSERT INTO paises (codigo, nombre) VALUES
  ('AFG', 'Afganistan'),
  ('ALB', 'Albania'),
  ('DEU', 'Alemania'),
  ('AND', 'Andorra'),
  ('AGO', 'Angola'),
  ('ATG', 'Antigua y Barbuda'),
  ('SAU', 'Arabia Saudita'),
  ('DZA', 'Argelia'),
  ('ARG', 'Argentina'),
  ('ARM', 'Armenia'),
  ('AUS', 'Australia'),
  ('AUT', 'Austria'),
  ('AZE', 'Azerbaiyan'),
  ('BHS', 'Bahamas'),
  ('BHR', 'Bahrein'),
  ('BGD', 'Bangladesh'),
  ('BRB', 'Barbados'),
  ('BEL', 'Belgica'),
  ('BLZ', 'Belice'),
  ('BEN', 'Benin'),
  ('BTN', 'Bhutan'),
  ('BLR', 'Bielorrusia'),
  ('MMR', 'Birmania (Myanmar)'),
  ('BOL', 'Bolivia'),
  ('BIH', 'Bosnia y Herzegovina'),
  ('BWA', 'Botsuana'),
  ('BRA', 'Brasil'),
  ('BRN', 'Brunei'),
  ('BGR', 'Bulgaria'),
  ('BFA', 'Burkina Faso'),
  ('BDI', 'Burundi'),
  ('CPV', 'Cabo Verde'),
  ('KHM', 'Camboya'),
  ('CMR', 'Camerun'),
  ('CAN', 'Canada'),
  ('QAT', 'Catar'),
  ('TCD', 'Chad'),
  ('CHL', 'Chile'),
  ('CHN', 'China'),
  ('CYP', 'Chipre'),
  ('VAT', 'Ciudad del Vaticano'),
  ('COL', 'Colombia'),
  ('COM', 'Comoras'),
  ('PRK', 'Corea del Norte'),
  ('KOR', 'Corea del Sur'),
  ('CIV', 'Costa de Marfil'),
  ('CRI', 'Costa Rica'),
  ('HRV', 'Croacia'),
  ('CUB', 'Cuba'),
  ('DNK', 'Dinamarca'),
  ('DMA', 'Dominica'),
  ('ECU', 'Ecuador'),
  ('EGY', 'Egipto'),
  ('SLV', 'El Salvador'),
  ('ARE', 'Emiratos Arabes Unidos'),
  ('ERI', 'Eritrea'),
  ('SVK', 'Eslovaquia'),
  ('SVN', 'Eslovenia'),
  ('ESP', 'España'),
  ('USA', 'Estados Unidos'),
  ('EST', 'Estonia'),
  ('ETH', 'Etiopia'),
  ('PHL', 'Filipinas'),
  ('FIN', 'Finlandia'),
  ('FJI', 'Fiyi'),
  ('FRA', 'Francia'),
  ('GAB', 'Gabon'),
  ('GMB', 'Gambia'),
  ('GEO', 'Georgia'),
  ('GHA', 'Ghana'),
  ('GRD', 'Granada'),
  ('GRC', 'Grecia'),
  ('GTM', 'Guatemala'),
  ('GUY', 'Guyana'),
  ('GNQ', 'Guinea Ecuatorial'),
  ('GIN', 'Guinea'),
  ('GNB', 'Guinea-Bisau'),
  ('HTI', 'Haiti'),
  ('HND', 'Honduras'),
  ('HUN', 'Hungria'),
  ('IND', 'India'),
  ('IDN', 'Indonesia'),
  ('IRQ', 'Irak'),
  ('IRN', 'Iran'),
  ('IRL', 'Irlanda'),
  ('ISL', 'Islandia'),
  ('MHL', 'Islas Marshall'),
  ('SLB', 'Islas Salomon'),
  ('ISR', 'Israel'),
  ('ITA', 'Italia'),
  ('JAM', 'Jamaica'),
  ('JPN', 'Japon'),
  ('JOR', 'Jordania'),
  ('KAZ', 'Kazajistan'),
  ('KEN', 'Kenia'),
  ('KGZ', 'Kirguistan'),
  ('KIR', 'Kiribati'),
  ('KWT', 'Kuwait'),
  ('LAO', 'Laos'),
  ('LSO', 'Lesoto'),
  ('LVA', 'Letonia'),
  ('LBN', 'Libano'),
  ('LBR', 'Liberia'),
  ('LBY', 'Libia'),
  ('LIE', 'Liechtenstein'),
  ('LTU', 'Lituania'),
  ('LUX', 'Luxemburgo'),
  ('MKD', 'Macedonia del Norte'),
  ('MDG', 'Madagascar'),
  ('MYS', 'Malasia'),
  ('MWI', 'Malaui'),
  ('MDV', 'Maldivas'),
  ('MLI', 'Mali'),
  ('MLT', 'Malta'),
  ('MAR', 'Marruecos'),
  ('MUS', 'Mauricio'),
  ('MRT', 'Mauritania'),
  ('MEX', 'Mexico'),
  ('FSM', 'Micronesia'),
  ('MDA', 'Moldavia'),
  ('MCO', 'Monaco'),
  ('MNG', 'Mongolia'),
  ('MNE', 'Montenegro'),
  ('MOZ', 'Mozambique'),
  ('NAM', 'Namibia'),
  ('NRU', 'Nauru'),
  ('NPL', 'Nepal'),
  ('NIC', 'Nicaragua'),
  ('NER', 'Niger'),
  ('NGA', 'Nigeria'),
  ('NOR', 'Noruega'),
  ('NZL', 'Nueva Zelanda'),
  ('OMN', 'Oman'),
  ('NLD', 'Paises Bajos'),
  ('PAK', 'Pakistan'),
  ('PLW', 'Palaos'),
  ('PAN', 'Panama'),
  ('PNG', 'Papua Nueva Guinea'),
  ('PRY', 'Paraguay'),
  ('PER', 'Peru'),
  ('POL', 'Polonia'),
  ('PRT', 'Portugal'),
  ('GBR', 'Reino Unido'),
  ('CAF', 'Republica Centroafricana'),
  ('CZE', 'Republica Checa'),
  ('COD', 'Republica Democratica del Congo'),
  ('COG', 'Republica del Congo'),
  ('DOM', 'Republica Dominicana'),
  ('RWA', 'Ruanda'),
  ('ROU', 'Rumania'),
  ('RUS', 'Rusia'),
  ('WSM', 'Samoa'),
  ('KNA', 'San Cristobal y Nieves'),
  ('SMR', 'San Marino'),
  ('VCT', 'San Vicente y las Granadinas'),
  ('LCA', 'Santa Lucia'),
  ('STP', 'Santo Tome y Principe'),
  ('SEN', 'Senegal'),
  ('SRB', 'Serbia'),
  ('SYC', 'Seychelles'),
  ('SLE', 'Sierra Leona'),
  ('SGP', 'Singapur'),
  ('SYR', 'Siria'),
  ('SOM', 'Somalia'),
  ('LKA', 'Sri Lanka'),
  ('SWZ', 'Suazilandia'),
  ('ZAF', 'Sudafrica'),
  ('SDN', 'Sudan'),
  ('SSD', 'Sudan del Sur'),
  ('SWE', 'Suecia'),
  ('CHE', 'Suiza'),
  ('SUR', 'Surinam'),
  ('THA', 'Tailandia'),
  ('TZA', 'Tanzania'),
  ('TJK', 'Tayikistan'),
  ('TLS', 'Timor Oriental'),
  ('TGO', 'Togo'),
  ('TON', 'Tonga'),
  ('TTO', 'Trinidad y Tobago'),
  ('TUN', 'Tunez'),
  ('TKM', 'Turkmenistan'),
  ('TUR', 'Turquia'),
  ('TUV', 'Tuvalu'),
  ('UKR', 'Ucrania'),
  ('UGA', 'Uganda'),
  ('URY', 'Uruguay'),
  ('UZB', 'Uzbekistan'),
  ('VUT', 'Vanuatu'),
  ('VEN', 'Venezuela'),
  ('VNM', 'Vietnam'),
  ('YEM', 'Yemen'),
  ('DJI', 'Yibuti'),
  ('ZMB', 'Zambia'),
  ('ZWE', 'Zimbabue')
ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre;
